-- ============================================================================
-- Arqueo de cuentas en el balance diario (conteo declarado vs sistema)
-- ============================================================================
-- Por cada cuenta, el usuario declara cuánto tiene FÍSICAMENTE. Se guarda el
-- saldo del sistema (snapshot), lo declarado y la diferencia. El "cerrar" solo
-- registra el conteo (NO mueve tesorería). Generar el ajuste de caja es OPCIONAL
-- (botón aparte): recién ahí la diferencia se asienta como movimiento de
-- tesorería (ref_tipo 'ajuste') y el saldo real queda = lo declarado.
-- No rompe la reconstrucción: si no se genera ajuste, el balance sigue igual.
-- ============================================================================

CREATE TABLE IF NOT EXISTS balance_cuenta_arqueos (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance_diario_id bigint       NOT NULL REFERENCES balances_diarios(id) ON DELETE CASCADE,
    cuenta_id         bigint       NOT NULL REFERENCES cuentas(id)          ON DELETE CASCADE,
    saldo_sistema     numeric(14,2) NOT NULL DEFAULT 0,   -- snapshot al guardar
    monto_declarado   numeric(14,2) NOT NULL DEFAULT 0,   -- lo que el usuario cuenta
    diferencia        numeric(14,2) NOT NULL DEFAULT 0,   -- declarado - sistema
    ajustado          boolean      NOT NULL DEFAULT false, -- ¿se generó ajuste de caja?
    ajuste_mov_id     bigint       NULL REFERENCES cuenta_movimientos(id) ON DELETE SET NULL,
    created_at        timestamp(0) NULL,
    updated_at        timestamp(0) NULL,
    CONSTRAINT balance_cuenta_arqueos_unique UNIQUE (balance_diario_id, cuenta_id)
);

CREATE INDEX IF NOT EXISTS idx_bal_arqueo_balance ON balance_cuenta_arqueos (balance_diario_id);
