-- ============================================================================
-- Ajustes de inventario: ingreso / salida de stock POR AJUSTE (sin dinero)
-- ============================================================================
-- Documento fuente para subir o bajar stock por cantidad, con fecha propia
-- (retrofechable), sin tocar tesorería/CxP/proveedor. Sale en el kardex y
-- sobrevive al "Recalcular stock" (Stock::reconstruir y kardex:reconstruir lo
-- cuentan como fuente). El signo lo da `tipo`: ingreso (+), salida (-).
-- cantidad_base siempre positiva. Sin costo propio: entra/sale al costo
-- promedio vigente (no diluye el CPP). Patrón del repo: SQL directo, sin migración.
-- ============================================================================

CREATE TABLE IF NOT EXISTS ajustes_inventario (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id    bigint      NOT NULL REFERENCES empresas(id)  ON DELETE CASCADE,
    almacen_id    bigint      NOT NULL REFERENCES almacenes(id) ON DELETE CASCADE,
    producto_id   bigint      NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
    user_id       bigint      NULL     REFERENCES users(id)     ON DELETE SET NULL,
    turno_id      bigint      NULL     REFERENCES turnos(id)    ON DELETE SET NULL,
    numero        varchar(20) NULL,                 -- correlativo AJ-0001 por empresa
    tipo          varchar(10) NOT NULL,             -- 'ingreso' | 'salida'
    cantidad_base numeric(14,4) NOT NULL,           -- siempre positiva; el signo lo da tipo
    fecha         date        NOT NULL,
    estado        varchar(20) NOT NULL DEFAULT 'borrador', -- 'borrador' | 'confirmado' | 'anulado'
    motivo        text        NULL,
    created_at    timestamp(0) NULL,
    updated_at    timestamp(0) NULL,
    CONSTRAINT ajustes_inventario_tipo_check   CHECK (tipo   IN ('ingreso','salida')),
    CONSTRAINT ajustes_inventario_estado_check CHECK (estado IN ('borrador','confirmado','anulado')),
    CONSTRAINT ajustes_inventario_cantidad_pos CHECK (cantidad_base > 0)
);

-- Sumas del recálculo por (almacén, producto, estado) filtrando por fecha.
CREATE INDEX IF NOT EXISTS idx_ajuste_inv_alm_prod_estado_fecha
    ON ajustes_inventario (almacen_id, producto_id, estado, fecha);
CREATE INDEX IF NOT EXISTS idx_ajuste_inv_empresa_fecha
    ON ajustes_inventario (empresa_id, fecha);

-- Correlativo AJ-0001 único por empresa (igual patrón que ventas/entregas).
CREATE UNIQUE INDEX IF NOT EXISTS ajustes_inventario_empresa_numero_unique
    ON ajustes_inventario (empresa_id, numero) WHERE numero IS NOT NULL;
